### ISSUE TITLE
Spatialite node.js module uses internal spatialite version instead of system one

### ISSUE THREAD

**Issue by joto** [osmcode/node-osmium#10]
The spatialite node.js module currently used in some demos of node-osmium and potentially very useful for some use cases uses its own copy of the spatialite library. If this is a newer version than the one installed on your system the files generated by it can not be read by other software on the system. This is currently an issue with debian which still uses spatialite version 3 while the node.js module uses version 4.

We could change the spatialite node.js module to use the system spatialite. Or maybe the spatialite code (which isn't a lot of code) could be rolled into the sqlite3 node.js module as an optional add-on or so.

**Comment by springmeyer** [comment]
Going to close, how the spatialite module works is out of scope for us.
