### ISSUE TITLE
Please release current build

### ISSUE THREAD

**Issue by tas50** [osmcode/node-osmium#116]
Hey there. There's a ton of great changes on the master branch right now that unblock users of new nodejs releases. Any chance you could ship what's there to make it easy to use this package with the latest nodejs. Thanks for creating this project.

**Comment by joto** [comment]
Unfortunately node-osmium is more or less abandoned. I am not using it myself and I am not paid any more to maintain it. So unless somebody steps up to keep maintaining it, there will be no more releases for the time being.
