### ISSUE TITLE
How can I access older versions of the same object in a historical (.osh.osm) file?

### ISSUE THREAD

**Issue by cmoffroad** [osmcode/node-osmium#118]
I've been experimenting with `node-osmium`, which works well with non-historical OSM files. However, my objective is to detect changes by comparing the latest object tags with older versions of the same object. Unfortunately, I haven't found a way to do this yet.

The `osmium getid` command indicates that the file I'm using contains historical versions, but when I use `node-osmium`, it only returns the latest version of the object. I've searched through the API documentation, but I couldn't find any method that gives access to other versions.

Is there a way to achieve this using the current library, or do I need to implement additional methods (e.g., `versions()`)?

I would greatly appreciate any pointers or guidance on how to tackle this issue.

**Comment by joto** [comment]
node-osmium is not supported any more, so I wouldn't spend time on implementing something new with it. Have a look at PyOsmium instead.

Both node-osmium any PyOsmium should give you access to all versions of all objects as they are in the input file, one after the other. You have to remember what the last object was and compare it to the current one.

**Comment by cmoffroad** [comment]
> node-osmium is not supported any more, so I wouldn't spend time on implementing something new with it. Have a look at PyOsmium instead.

Alright, I'll actually use the osmium command line tools and some bash scripts from now on.

Also, it might be beneficial to include a more noticeable warning on the GitHub homepage for others, similar to this one:
<img width="1279" alt="Screen Shot 2567-04-14 at 21 57 11" src="https://github.com/osmcode/node-osmium/assets/2485196/37474cc0-bd91-41c8-bd8b-71d442f6e47f">
