### ISSUE TITLE
Buffered file output?

### ISSUE THREAD

**Issue by joto** [osmcode/node-osmium#21]
Two demos (csv-output and relation-tree) use the [buffered-writer](https://github.com/Gagle/Node-BufferedWriter) module which is deprecated. The github page says to use the nodejs Buffer class, but I don't see how this can be used without checking the buffer for size every once in a while an flushing it.

**Comment by springmeyer** [comment]
Just landing here when looking at my backlog of assigned tickets. Going to unassign myself now. @rclark I wonder if you have new insights on this based on your tilelive work?

**Comment by rclark** [comment]
^^ I think the above commit fixes the data corruption that @joto found. I published a v1.1.0 if you want to give it another run.

**Comment by springmeyer** [comment]
This is an awesome discussion to follow. Not seeing any next actions, other than to say that:

```
buffered.write('\nGoodnight, moon!');
```

^^ is a favorite part of this issue for me:

![](https://slowcookerchili.files.wordpress.com/2014/10/cropped-il_fullxfull-233231639.jpg)
