### ISSUE TITLE
streaming interface

### ISSUE THREAD

**Issue by missinglink** [osmcode/node-osmium#31]
heya, I saw some discussion going on around a stream interface so I threw one together today, which you can either merge in to core or leave as a separate module ;)

https://github.com/geopipes/osmium-stream

When I tried some of the demo code which exhibited streaming interfaces I found that they blocked the event loop, which meant I couldn't do anything outside of the `handler.on` [event handlers](https://github.com/osmcode/node-osmium/blob/master/demo/geojson-stream/index.js#L38).

...you can play with this yourself by adding a `setInterval( console.log.bind( console, 'making bacon pancakes' ), 1000 );` and you'll see it doesn't fire much when using `handler.on()`.

The main issue this module solves is backpressure, if a downstream pipe is being slow (like a db connection) then this module will propagate the pressure upstream and pause the osmium iterator until the pressure subsides, meaning no memory leaks, buffering or segfaults FTW.

IMHO this is the `'nicest'` interface for nodejs as it's reminiscent of unix pipes, for a working example see: https://github.com/geopipes/osmium-stream/blob/master/test/example.js

**Comment by joto** [comment]
@missinglink, @rclark: I have now implemented a (hopefully) better streaming interface based on the ideas from @missinglink. It is derived from the NodeJS readable stream and so it doesn't have the different callbacks for nodes, ways, and relations any more. Instead one 'data' callback is used.

It is all a bit clunky still, setting everything up is not super-intuitive, but it can handle all the cases, including the different node location stores and multipolygon support. You can have a look at the `demo/stream` example to see how it works. The `Converter` stuff also uses the new `Stream` interface, see `demo/converter`. Please try it out. If this is going in the right direction, I'll clean it up etc. The old `Handler` interface is obsolete with this now and can probably go away.

**Comment by missinglink** [comment]
hey @joto that sounds awesome! I'm off on annual leave today but I'll be sure to check it out when I'm back.

**Comment by springmeyer** [comment]
v0.4.0 release is out with a new streaming interface, @joto - are their docs for it?

**Comment by joto** [comment]
No docs, you have to look at the included demos.

**Comment by springmeyer** [comment]
Okay, closing this with some references to example code:

 - https://github.com/osmcode/node-osmium/blob/d87ed8ffc64f120e7318dda7fd11cd7af2d6a254/test/basic_reader.test.js#L37-L65
 - https://github.com/osmcode/node-osmium/blob/d87ed8ffc64f120e7318dda7fd11cd7af2d6a254/demo/stream/index.js
 - https://github.com/osmcode/osmium-suite/tree/2d8dfb0294aeee257e443ea0547aabb911209e05/benchmarks/count_nodes_with_tag
 - https://github.com/rclark/osm2geojson/blob/6febc9a53d0688724f328969aff75ccd7626ed58/index.js
