### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#32]
A ticket to track supporting windows.

 - [x] Add appveyor config
 - [x] Try to use same SDK used for libosmium to compile node-osmium against
 - [x]  Fix compile errors, test failures

**Comment by BergWerkGIS** [comment]
@joto @springmeyer 

First working version of AppVeyor.yml:
https://github.com/BergWerkGIS/node-osmium/blob/master/appveyor.yml

Also made some inital changes to `binding.gyp` and `common.gpyi`
https://github.com/BergWerkGIS/node-osmium/compare/osmcode:master...master

Some compile errors:

[`libosmium\include\osmium/io/detail/read_write.hpp(46): error C2371: 'ssize_t': redefinition`](https://ci.appveyor.com/project/BergWerkGIS/node-osmium/build/1.0.2#L61)

[`..\src\handler.cpp(184): error C2466: cannot allocate an array of constant size 0`](https://ci.appveyor.com/project/BergWerkGIS/node-osmium/build/1.0.2#L122)

[`..\src\handler.cpp(184): error C2440: 'initializing': cannot convert from 'int' to 'v8::Local<v8::Value>'`](https://ci.appveyor.com/project/BergWerkGIS/node-osmium/build/1.0.2#L123)

**Comment by joto** [comment]
* Okay, I have merged your changes.
* The first error (redefinition) is in some code that was specifically added for Windows support. Maybe thats not needed any more in the newest compiler version? @BergWerkGIS: Can you investigate? Try removing the `typedef` and see whether that fixes things.
* Other errors: `handler.cpp` is probably going away anyway, so the errors don't matter much. I have to clean up that code.

**Comment by joto** [comment]
Appveyor build doesn't find `osmpbf.lib`:
`[00:05:19] LINK : fatal error LNK1181: cannot open input file 'osmpbf.lib' [C:\projects\node-osmium\build\osmium.vcxproj]`

@BergWerkGIS can you fix this?

**Comment by BergWerkGIS** [comment]
`osmpbf.lib ` fixed: 
https://github.com/BergWerkGIS/node-osmium/commit/f50684bbdd2d60f81aa9a4b7da74da8081642291

But getting this error locally:
```
multipolygon_collector_wrap.obj : error LNK2005: "class std::chrono::duration<__int64,struct std::ratio<1,1000> > osmium::thread: :full_queue_sleep_duration" (?full_queue_sleep_duration@thread@osmium@@3V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@A) alr eady defined in apply.obj [c:\mb\node-osmium\build\osmium.vcxproj]
multipolygon_handler_wrap.obj : error LNK2005: "class std::chrono::duration<__int64,struct std::ratio<1,1000> > osmium::thread::f ull_queue_sleep_duration" (?full_queue_sleep_duration@thread@osmium@@3V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@A) alrea dy defined in apply.obj [c:\mb\node-osmium\build\osmium.vcxproj]
node_osmium.obj : error LNK2005: "class std::chrono::duration<__int64,struct std::ratio<1,1000> > osmium::thread::full_queue_slee p_duration" (?full_queue_sleep_duration@thread@osmium@@3V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@A) already defined in
apply.obj [c:\mb\node-osmium\build\osmium.vcxproj]
basic_reader_wrap.obj : error LNK2005: "class std::chrono::duration<__int64,struct std::ratio<1,1000> > osmium::thread::full_queu e_sleep_duration" (?full_queue_sleep_duration@thread@osmium@@3V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@A) already defin ed in apply.obj [c:\mb\node-osmium\build\osmium.vcxproj]
flex_reader_wrap.obj : error LNK2005: "class std::chrono::duration<__int64,struct std::ratio<1,1000> > osmium::thread::full_queue _sleep_duration" (?full_queue_sleep_duration@thread@osmium@@3V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@A) already define d in apply.obj [c:\mb\node-osmium\build\osmium.vcxproj]
```

**Comment by joto** [comment]
That was a bug in libosmium already fixed in df5d6c9b5605ea397e653fe511e9bb5ca866d8ba.

**Comment by joto** [comment]
Aeh. I meant now fixed in 0b24814. :)

**Comment by BergWerkGIS** [comment]
ok, that one is gone.

New one:
```
  Finished generating code
* CIL library *(* CIL module *) : error LNK2005: "public: char * __cdecl v8::String::Utf8Value::operator*(void)" (??DUtf8Value@St ring@v8@@QEAAPEADXZ) already defined in node.lib(node.exe) [c:\mb\node-osmium\build\osmium.vcxproj]
c:\mb\node-osmium\build\Release\osmium.node : fatal error LNK1169: one or more multiply defined symbols found [c:\mb\node-osmium\ build\osmium.vcxproj]
```

**Comment by BergWerkGIS** [comment]
Looks like an `/MT` vs `/MD` error.
@springmeyer  any idea, why this is happening here and not with node-mapnik?

**Comment by springmeyer** [comment]
@BergWerkGIS - yes, it does look like that. This did used to happen with node-mapnik, but recently I found I could remove the workaround without the `multiply defined symbols` errors re-appearing: https://github.com/mapnik/node-mapnik/pull/383.

Maybe what is happening is that the default appveyor node (non c++11 build /MT linked one) is conflicting? Maybe you need to remove it like https://github.com/mapnik/node-mapnik/blob/master/appveyor.yml#L39?

**Comment by BergWerkGIS** [comment]
Made it compile locally, but tests are stuck here for more than 1/2 hour now at ~30% CPU:

![image](https://cloud.githubusercontent.com/assets/4549888/6987608/40a238b2-da49-11e4-9c52-7378df7870c0.png)

**Comment by joto** [comment]
The multiple definition error was fixed in 58a6952cea000dc5e601bcc5de36bb64a3226dad.

**Comment by joto** [comment]
Appveyor build is okay now. Last messages are:
```
Discovering tests...OK
Build success
```
Does that mean it actually ran the tests?

Tests should run in 2 seconds or so. Debugging the hanging test is difficult. Try removing it and then lets look at the debug output from the other tests and fix the failing tests first. If we are lucky we'll fix the hanging test in the process.

**Comment by BergWerkGIS** [comment]
Latest build, 12 minutes ago, is also successful:
https://ci.appveyor.com/project/BergWerkGIS/node-osmium/build/1.0.8

> Does that mean it actually ran the tests?

No, AppVeyor is looking for .Net Framework tests.
Disabled discovery of .Net tests.
Enabled npm tests.
Disabled test `should be able to stream buffer created from a file`

Running:
https://ci.appveyor.com/project/BergWerkGIS/node-osmium/build/1.0.9

**Comment by joto** [comment]
Those test failures were due to the use of the `winthrop.osm.ser` file which uses the internal Osmium OSM data format. Unfortunately this format depends on the architecture/compiler, so Windows will not be able to read one created from Linux. I have fixed the tests and updated the Appveyor config and it all runs successfully now.

**Comment by joto** [comment]
All done!
