### ISSUE TITLE
Node v0.12.x support

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#37]
We should start working on supporting node v0.12.x. What this will take is:

 - [ ] Port the code to use [nan](https://github.com/iojs/nan) <-- this supports node as well as io.js, but we'll use only to get node-osmium working against both node v0.10.x and v0.12.x simultaneously with the least effort.
 - [ ] Modify the .travis.yml and appveyor configs to start testing and building binaries for node v0.12.x

**Comment by rclark** [comment]
@springmeyer are these steps still applicable for node 0.12, 4.x and 5.x?

**Comment by springmeyer** [comment]
> @springmeyer are these steps still applicable for node 0.12.x, 4.x and 5.x?

@rclark yes - see #73

**Comment by springmeyer** [comment]
#73 is now merged. We are not providing binaries for v0.12.x, but rather v4 and v5 as of node-osmium@0.5.0
