### ISSUE TITLE
v0.4.0 release

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#38]
It's time for a new release! This release will include at least:

 - latest libosmium features (/cc @joto to list these out)
 - first windows support

**Comment by springmeyer** [comment]
Todo before release:

 - [ ] appveyor publishing: https://github.com/osmcode/node-osmium/issues/39

**Comment by rclark** [comment]
Bump! I would really like to use the new streaming interface.

**Comment by BergWerkGIS** [comment]
@rclark FYI: I'm blocked by other things for at least this week.
Planing on looking into this during next week.

**Comment by springmeyer** [comment]
@joto - let's march ahead on the new release and not worry about windows binaries for the time being. So, I think the only thing needed for a release are:

  - [ ] all travis builds working and tests passing
  - [ ] @joto gives the go ahead to release
  - [ ] @joto creates linux and mac binaries by pushing to master with a commit like `git commit --allow-empty -m "[republish binary] v0.4.0"
  - [ ] @joto creates and uploads tag `git tag -a -m "v0.4.0"`
  - [ ] @springmeyer runs `npm publish`
  - [ ] close this ticket

**Comment by springmeyer** [comment]
`osmium@0.4.0` is released, closing.
