### ISSUE TITLE
Rename apply() function?

### ISSUE THREAD

**Issue by joto** [osmcode/node-osmium#44]
There is an `osmium.apply()` function named after the same function in C++. Unfortunately the function `apply()` is used in Javascript already, every function object has it. Naming our own function `apply()` is potentially confusing for experiences Javascript developers. At the moment I am not seeing any actual problems with it, but there could be.

Should we rename our function? Any opinions on this?

**Comment by springmeyer** [comment]
Let's keep things as they are.
