### ISSUE TITLE
prb with install 

### ISSUE THREAD

**Issue by idir-ait** [osmcode/node-osmium#46]
i have this msg :/

$ node -v
v0.12.5
$ npm install osmium
npm WARN engine osmium@0.3.0: wanted: {"node":">= 0.10.0 < 0.11.0"} (current: {"node":"0.12.5","npm":"2.11.2"})

> osmium@0.3.0 install /home/julien/node_modules/osmium
> node-pre-gyp install --fallback-to-build

[osmium] Command failed: /usr/local/bin/node --eval require('/home/julien/node_modules/osmium/lib/binding/osmium.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /home/julien/node_modules/osmium/lib/binding/osmium.node: invalid ELF header
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/julien/node_modules/osmium/build'
  CXX(target) Release/obj.target/osmium/src/apply.o
../src/apply.cpp:3:29: fatal error: boost/variant.hpp: No such file or directory
compilation terminated.
make: *** [Release/obj.target/osmium/src/apply.o] Error 1
make: Leaving directory `/home/julien/node_modules/osmium/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=osmium" "--configuration=Release" "--module_name=osmium" "--version=0.3.0" "--minor=3" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/osmium.js" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/home/julien/node_modules/osmium/lib/binding" "--module=/home/julien/node_modules/osmium/lib/binding/osmium.node" "--remote_path=./osmium/v0.3.0/" "--package_name=node-v14-linux-x64.tar.gz" "--staged_tarball=build/stage/osmium/v0.3.0/node-v14-linux-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-linux-x64.tar.gz"
gyp ERR! cwd /home/julien/node_modules/osmium
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=osmium --configuration=Release --module_name=osmium --version=0.3.0 --minor=3 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/osmium.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/home/julien/node_modules/osmium/lib/binding --module=/home/julien/node_modules/osmium/lib/binding/osmium.node --remote_path=./osmium/v0.3.0/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/osmium/v0.3.0/node-v14-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/julien/node_modules/osmium/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.2.0-4-amd64
node-pre-gyp ERR! command "node" "/home/julien/node_modules/osmium/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/julien/node_modules/osmium
node-pre-gyp ERR! node -v v0.12.5
node-pre-gyp ERR! node-pre-gyp -v v0.5.27
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=osmium --configuration=Release --module_name=osmium --version=0.3.0 --minor=3 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/osmium.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/home/julien/node_modules/osmium/lib/binding --module=/home/julien/node_modules/osmium/lib/binding/osmium.node --remote_path=./osmium/v0.3.0/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/osmium/v0.3.0/node-v14-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-linux-x64.tar.gz' (1)
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "osmium"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! osmium@0.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osmium@0.3.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the osmium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls osmium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/julien/node_modules/npm-debug.log

**Comment by springmeyer** [comment]
what version of linux are you using?

**Comment by idir-ait** [comment]
Debian

**Comment by springmeyer** [comment]
should be fixed by the v0.4.0 release (#38)
