### ISSUE TITLE
Appveyor builds failing

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#50]
https://ci.appveyor.com/project/Mapbox/node-osmium/history

Error that started recently is:

```
node -v
Command exited with code -1073741515
```

I presume this is because of things moving around on S3. /cc @BergWerkGIS to see if he sees a quick fix.

**Comment by springmeyer** [comment]
Realizing that we'll need to get a new vs 2015 SDK going to solve this, which will take some time and is lower priority than other items @BergWerkGIS is working on. So, @joto - windows builds will be failing for a bit :)

**Comment by BergWerkGIS** [comment]
TODO:

* [ ] Upgrade AppVeyor.yml to 2015 image
* [ ] build and provide new binary deps package with VS2015

**Comment by BergWerkGIS** [comment]
green: https://ci.appveyor.com/project/Mapbox/node-osmium/build/1.0.34
