### ISSUE TITLE
Pin to libosmium release for binary builds

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#53]
Our travis script (and therefore binary packages) always pull from latest master libosmium. How about we start pulling from a tagged version? 

 - https://github.com/osmcode/node-osmium/blob/master/.travis.yml#L61

/cc @joto

**Comment by joto** [comment]
I have updated the release instructions in https://github.com/osmcode/osmium-suite/blob/master/make_releases.md . We'll do it on the next release.

**Comment by joto** [comment]
This is now done for travis and appveyor.
