### ISSUE TITLE
processing order for map elements

### ISSUE THREAD

**Issue by matiasdahl** [osmcode/node-osmium#56]
In practice it seems element handlers first receives all nodes, then all ways, and finally all relations. Also, elements arrive with increasing id numbers, and if there are multiple versions, they are processed in chronological order. 

The above order is probably fixed by the OSM export tool. However, for some applications it would be good to know the order when writing the handler. For example:

- If one is not using the built-in LocationHandler, one would need to know that all nodes are processed before ways and relations. 

- If one would like to extract the last version of each map element from an export with multiple versions, then this can be done simply (by just keeping track of the previous entry in the handler) if we know that elements arrive in the above order. 

I don't know how this is best addressed. If the order is part of the specs for the OSM file formats, one can just add a guarantee to the documentation. An alternative is to add a test to any element handler that depend on a specific order. See for example [this script](https://github.com/matiasdahl/osm-extract-amenities/blob/master/extract-amenity-type.js#L107). This script aborts if elements do not arrive in the correct order.

**Comment by joto** [comment]
This is outside the scope of osmium or node-osmium. Node-osmium will simply call the callbacks in the order the objects are in the file. It depends on where you got the file from whether that file is ordered in any way or not. You have to ask the source whether the file is guaranteed to be ordered in some way or not and build your application accordingly. There is no way for (node-)osmium to know whether a file is ordered without reading the whole file first.

Checking in the handler for the right order and aborting if it is not kept like you are doing is probably a good idea to make your program more robust. But not everybody needs the ordering or maybe they only need a partial ordering. The location handler for instance only needs all nodes needed in each way to be in the file before that way, thats much less than a complete ordering.
