### ISSUE TITLE
Provide a way to get the geometry of route relations

### ISSUE THREAD

**Issue by lucaswoj** [osmcode/node-osmium#57]
The geometry of multipolygon relations can be read with a `MultipolygonCollector` but no such utility exists for _route_ relations.

**Comment by lucaswoj** [comment]
Guessing this would be implemented by exposing the (`osmium::relations::Collector`)[https://github.com/osmcode/libosmium/blob/master/include/osmium/relations/collector.hpp] class to JS

**Comment by joto** [comment]
Unfortunately exposing the C++ classes to Javascript is hard and will probably not work in this case, because of the heavily templated code. Solution would probably be to write a RouteCollector class in C++ and expose its result to Javascript. Or do the whole route collection in Javascript.

**Comment by springmeyer** [comment]
Closing as non-actionable since it would be a good amount of work. @lucaswoj - re-open if this is a priority of blocking you.
