### ISSUE TITLE
Odd memory usage with small XML files

### ISSUE THREAD

**Issue by rclark** [osmcode/node-osmium#67]
https://gist.github.com/rclark/eb01727e665ae1e2323c demonstrates a script that takes a small OSM XML snippet and repeatedly passes it through node-osmium to create geojson. 

When I run this script and track the process memory usage, it seems to cycle, growing to over 1GB and dropping again, spending a lot of time hovering around 500MB. If you decrease the interval and make the function run faster, the memory spikes get larger, I saw as high as 5GB. I see similar memory usage even if I remove the `handler.on('area')` function entirely.

I understand that this is not a use-case that node-osmium was really designed for, but I've run into it while trying to deal with "atomic" OSM data events, and curious what you think. 

cc @joto @springmeyer

**Comment by rclark** [comment]
After a little more hunting with @springmeyer, the problem seems to come up when "closing" is handled in a function vs. at a top level. See https://gist.github.com/rclark/eb01727e665ae1e2323c#file-catch-memory-spikes-js-L16-L27

**Comment by BergWerkGIS** [comment]
@rclark what's the CPU usage when you run those scripts?
During debugging node-mapnik I came across similar patterns (although a proj4 bug also played a role then).
My impression was that node somtetimes defers garbage collection when under heavy load.
GC seems to happen when node is not at 100% CPU.
Heavy load might also be responsible for events to take longer to fire (no free CPU cycles to do so).

**Comment by rclark** [comment]
I think you may be onto something with the original gist and my description of cyclical RAM usage. However I updated the gist and should have updated the comment: with the "leak" configuration (Option B), I see unchecked RAM growth, not a periodic collection like I was seeing before. With Option A, there is no memory leak. It seems to me that somehow `reader.close()`, when called from inside a function, isn't releasing the memory that its supposed to?

**Comment by joto** [comment]
`reader.close()` doesn't release any memory at all. It does some cleanup, but that cleanup should already have happened when the file is read until the end (which `apply()`) will do). And the cleanup doesn't include freeing any large memory spaces anyway.

Could you try all of this using the Stream interface instead of the handler. The handler is basically deprecated because it can't handle backpressure like the Stream interface can. See `demo/stream` for the interface.

**Comment by rclark** [comment]
Using the stream interface I can't replicate the leak. Feel free to close if the handler interface is deprecated and won't be fixed.
