### ISSUE TITLE
Hard failure on bad data file

### ISSUE THREAD

**Issue by rclark** [osmcode/node-osmium#70]
The following gist demonstrates a case where node-osmium fails when simply reading an xml file: https://gist.github.com/rclark/b957f10a435a8c71827e

Error message looks like this:
```
node: ../../libosmium/include/osmium/osm/node_ref_list.hpp:92: const osmium::NodeRef &osmium::NodeRefList::front() const: Assertion `!empty()' failed.
```

My initial suspicion was that the data file is bad (which it is) -- there are a number of ways included in the file without any references to nodes:

```xml
    <way changeset="32919043" id="362662527" timestamp="2015-07-27T21:35:46Z" uid="188704" user="Karta" version="1"/>
    <way changeset="32918129" id="362658561" timestamp="2015-07-27T20:45:32Z" uid="188704" user="Karta" version="1"/>
    <way changeset="32918129" id="362658337" timestamp="2015-07-27T20:44:39Z" uid="188704" user="Karta" version="1"/>
    <way changeset="32918356" id="362660420" timestamp="2015-07-27T21:07:29Z" uid="188704" user="Karta" version="1"/>
    <way changeset="32918356" id="362660287" timestamp="2015-07-27T21:03:57Z" uid="188704" user="Karta" version="1"/>
    <way changeset="32918356" id="362660719" timestamp="2015-07-27T21:12:34Z" uid="188704" user="Karta" version="1"/>
    <way changeset="34673665" id="362660218" timestamp="2015-10-16T11:42:30Z" uid="463879" user="tumsi" version="3"/>
    <way changeset="32918356" id="362660523" timestamp="2015-07-27T21:11:10Z" uid="188704" user="Karta" version="2"/>
```

However, I couldn't reproduce the problem by just isolating those ways.

My biggest concern here is not that node-osmium fails on this crummy data file, but that it fails in such a way that the error cannot be caught and handled within node.js.

cc @joto

**Comment by rclark** [comment]
oops @joto I had forgotten some prior conversation we had about this. Do you think that https://github.com/osmcode/libosmium/commit/657579bb27018d2af15266a04d13c90190aeee71 applies to this case? If so, can we consider a patch bump on node-osmium to pre-bundle with a new libosmium?

**Comment by springmeyer** [comment]
With `osmium@osmium@0.4.4` and the testcase (https://gist.github.com/rclark/b957f10a435a8c71827e) on OS X I don't see an assertion/abort but rather a JS error:

```
$ node a-simple-test.js 

/Users/dane/projects/b957f10a435a8c71827e/node_modules/osmium/lib/osmium.js:84
            this._reader = new osmium.FlexReader(file, location_handler);
                           ^
TypeError: XML parsing error at line 5707, column 4: unclosed token
    at new exports.Reader (/Users/dane/projects/b957f10a435a8c71827e/node_modules/osmium/lib/osmium.js:84:28)
    at Object.<anonymous> (/Users/dane/projects/b957f10a435a8c71827e/a-simple-test.js:5:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
~/projects/b957f10a435a8c71827e[master]$ npm ls osmium
/Users/dane/projects/b957f10a435a8c71827e
└── osmium@0.4.4 

```

**Comment by rclark** [comment]
@springmeyer like I said yesterday, the gist truncated the data file so that led to your seeing an XML parsing error in JS. 

The good news is, I just came across an XML doc that hits the assertion and crashes in node-osmium@0.4.4, but does not crash in node-osmium@0.4.5. Thanks for the build!
