### ISSUE TITLE
segfault when applying backpressure to osmium read stream 

### ISSUE THREAD

**Issue by emilymcafee** [osmcode/node-osmium#72]
@joto @springmeyer I'm using node-osmium to parse changefiles and seeing: 

`[  401.635084] node[8012]: segfault at 7f4785440818 ip 00007f478e55a815 sp 00007ffe400830a0 error 4 in osmium.node[7f478e4d2000+10f000]`

Setup is like:

- read stream from file on s3
- gunzip
- write to tmp file
- create osmium read stream from tmp file with `new osmium.Stream(new osmium.Reader(new osmium.File(filepath)));`
- pipe through transform stream to extract some information from each feature (id, type, version) 
- batch features and send off messages about each batch

In that final step, I'm exerting a lot of backpressure on the stream - via setting a highwatermark and implementing a 1-second pause for each batch -- so... reading from the osmium stream very slowly. 

For a given file, it seems to segfault at roughly the same place each time (but this place is different for different changefiles). Here's the file I've been testing with, although I've had different changefiles cause this as well. http://planet.osm.org/replication/changesets/000/022/999.osm.gz 

Any idea what's going on?

cc @rclark

**Comment by joto** [comment]
This is unlikely to have anything to do with the backpressure. The files are so small that they will be completely read into memory anyway. I'll need the code you are using to reproduce this and debug it any further.

btw: Osmium can do the uncompress itself (will do this automatically if the file ends in `.gz`) and it can also directly read from http, just give it a URL instead of a filename.

**Comment by springmeyer** [comment]
bump: node-osmium v0.5.0 is now out with node v4/5 support and using libosmium 2.6.1. @emilymcafee - I would be interested to know if you can still replicate with this new version?

**Comment by emilymcafee** [comment]
@springmeyer @joto I ended up reverting to a [sax](https://www.npmjs.com/package/sax) based parser, and afaik we don't need the speed gains from using node-osmium anymore. I'll re-open if we circle back to this implementation and still have problems, though. Thanks!
