### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#74]
Seeing:

```
C:\projects\libosmium\include\osmium/osm/timestamp.hpp(229): error C2589: '(': illegal token on right side of '::' (compiling source file ..\src\filter.cpp) [C:\projects\node-osmium\build\osmium.vcxproj]
C:\projects\libosmium\include\osmium/osm/timestamp.hpp(229): error C2059: syntax error: '::' (compiling source file ..\src\filter.cpp) [C:\projects\node-osmium\build\osmium.vcxproj]
C:\projects\libosmium\include\osmium/util/cast.hpp(79): warning C4003: not enough actual parameters for macro 'min' (compiling source file ..\src\filter.cpp) [C:\projects\node-osmium\build\osmium.vcxproj]
```

Looks like it is libosmium related. Libosmium appveyor is green (https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.394) so perhaps this is failing because node-osmium pulls in headers that libosmium build on window does not?

https://ci.appveyor.com/project/Mapbox/node-osmium/build/1.0.82#L86

/cc @joto @BergWerkGIS

**Comment by joto** [comment]
The code in these places is `std::numeric_limits<T>::max()` which is correct code. Also the right include (`limits`) is done. From the error messages it looks to me like there is a macro `max()` defined that's screwing up things. It seems this here is our problem: https://support.microsoft.com/en-us/kb/143208 .

So we need to compile with the equivalent if `-DNOMINMAX` on Windows, but I don't know where to put that.

**Comment by springmeyer** [comment]
Great, thanks @joto - that solved the compile error. Now the tests are failing, but thats a new issue (first time we've gotten this far). Will open a separate issue for that.
