### ISSUE TITLE
Get node-osmium tests passing against latest libosmium

### ISSUE THREAD

**Issue by springmeyer** [osmcode/node-osmium#80]
@joto - can you take a look at creating a branch of node-osmium that runs against the latest libosmium (with all that exciting new, more robust and faster multipolygon assembly code)?

Note: Locally of course you'll configure things as you wish, but in terms of getting your branch passing on travis you should just be able to branch node-osmium, change https://github.com/osmcode/node-osmium/blob/d87ed8ffc64f120e7318dda7fd11cd7af2d6a254/package.json#L4 to a gitsha or branch name, and then push to travis.

Locally I see that things compile just fine. But we have failing tests that look like: https://gist.github.com/springmeyer/48df5a5fcd66340aef9ff463fb977148. To get the tests passing we might need to update to the latest test data: https://github.com/osmcode/osm-testdata/issues/9 and adapt the tests a bit: https://github.com/osmcode/node-osmium/blob/master/test/osm-testdata.test.js

/cc @rclark @aaronlidman

**Comment by springmeyer** [comment]
More details on plan: I'll create a branch right now and publish some dev binaries for @rclark to test. Then tomorrow @joto will take a look at fixing the tests in that branch.

**Comment by springmeyer** [comment]
@rclark binaries are ready:

```json
"dependencies": {
  "osmium": "https://github.com/osmcode/node-osmium/tarball/latest-libosmium"
}
```

**Comment by joto** [comment]
The reason those tests failed was simple: In old libosmium code whenever a multipolygon was invalid, an "empty" area object (with no rings) was created. The new libosmium code by default just ignored those areas and did output nothing at all. I have now changed the behaviour in libosmium master to, again, by default create those empty areas, but it is still configurable. Locally the tests now run all through.

**Comment by springmeyer** [comment]
great, they are passing now. So current node-osmium master @d87ed8f works great and all tests pass against latest libosmium master at bde10c4. Going to close this then. Will keep alive the `latest-libosmium` branch however as a mechanism to continue pushing dev builds for @rclark as he needs.
