### ISSUE TITLE
Array and disk LocationHandlers

### ISSUE THREAD

**Issue by ajashton** [osmcode/node-osmium#81]
@joto I'm trying to use node-osmium with either the array or disk LocationHandler option but I'm getting this for both of them:

```
var location_handler = new osmium.LocationHandler("array");
                       ^
TypeError: Support for map type 'array' not compiled into this binary.
    at Object.<anonymous> (/home/aj/Code/osm-databot/bin/builtup/import.js:35:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

I've tried both the version from NPM and compiling my own version. How can I enable these features when compiling node-osmium myself? Would it be possible to get them in the NPM binary?

**Comment by joto** [comment]
There is no `array` location handler. Usually you have `sparse_mem_array` and `sparse_mmap_array` available for small files and `dense_mem_array` and `dense_mmap_array` for full planet or large extracts. On Linux use the `*_mmap_*` version, on OSX the `*_mem_*` version. Use `*_file_array` instead if you don't have enough main memory. You'll need over 32GB for `dense` arrays these days. More details here: http://docs.osmcode.org/osmium-concepts-manual/#indexes

The naming of those index types changed at some point, but that was a long time ago.

**Comment by ajashton** [comment]
Okay, thanks. I got the 'array' and 'disk' names from the [tutorial in this repo](https://github.com/osmcode/node-osmium/blob/master/doc/tutorial.md#the-locationhandler).

**Comment by joto** [comment]
Ah, thanks for the info @ajashton . Totally out of date. I have updated it.
