### ISSUE TITLE
Console output in handler hangs and memory overflows

### ISSUE THREAD

**Issue by joto** [osmcode/node-osmium#85]
When running the following script and sending output to file, everything will be okay. But when sending to console, output will stop after a while and the program will draw memory until it is killed by nodejs.

```
"use strict";

var osmium = require('osmium');
var reader = new osmium.Reader("some_file.osm.pbf");
var handler = new osmium.Handler();

var object_handler = function(map_obj) {
  /* dummy handler. Print map id. */
  console.log(map_obj.id)
};

handler.on("node", object_handler);
osmium.apply(reader, handler);
```

Using the `stream` interface instead of the `handler` interface this works okay.

**Comment by henningvs** [comment]
Is there a workaround or small example how to use the stream interface together with node? 
I tried to parse through the planet-osm but the memory usage kills my machine unfortunately.

**Comment by joto** [comment]
https://github.com/osmcode/node-osmium/tree/master/demo/stream and https://github.com/osmcode/node-osmium/blob/master/demo/geojson-stream/index.js.
