### ISSUE TITLE
‘osmium::area::Assembler::config_type’ has no member named ‘keep_type_tag’

### ISSUE THREAD

**Issue by julianrubisch** [osmcode/node-osmium#87]
Node-osmium install is failing with the following errors:

```
In file included from ../src/apply.cpp:18:0:
../src/multipolygon_collector_wrap.hpp: In static member function ‘static osmium::area::Assembler::config_type node_osmium::MultipolygonCollectorWrap::default_assembler_config()’:
../src/multipolygon_collector_wrap.hpp:22:20: error: ‘osmium::area::Assembler::config_type’ has no member named ‘keep_type_tag’
             config.keep_type_tag = true;
```

I installed all the dependencies, including the OSM-binary (in the project directory). I'm on Ubuntu 16.04, node v0.12.15, node-gyp v3.2.1, node-pre-gyp v0.6.30 and npm v2.15.1

```
CC=gcc-4.8
CXX=g++-4.8
```

This strikes me as a weird error, do you have any pointers for me?

**Comment by joto** [comment]
Your libosmium is tool old. You can not use the package from Ubuntu. Get the [latest release form github](https://github.com/osmcode/libosmium/releases/latest).

**Comment by julianrubisch** [comment]
Alright, thanks! Maybe mention this in the README, though? 

It states "(Debian/Ubuntu: libosmium2-dev)" under requirements.
