### ISSUE TITLE
v6/v7 node support

### ISSUE THREAD

**Issue by ramyaragupathy** [osmcode/node-osmium#89]
**Issue:** [Installation failure](https://gist.github.com/ramyaragupathy/83ce1db56804da19a629db99fda4fa0a) on a computer with node v7.9.0

**Steps to reproduce:**
1. `brew install node`
2.  `npm install osmium`

Per conversation w/ @springmeyer, node v4 supports osmium setup. Still filing an issue to keep track of v7 support

**Comment by joto** [comment]
It seems there is no pre-built library available and the fallback to source build doesn't work, because libosmium isn't installed. The README is outdated and not very clear on how to do an install when the pre-built libs aren't availble.

**Comment by springmeyer** [comment]
node v6 binaries landed in 0.5.1 (https://github.com/osmcode/node-osmium/blob/master/CHANGELOG.md#051---2016-07-21) and v8 binaries in 0.5.5 (https://github.com/osmcode/node-osmium/blob/master/CHANGELOG.md#055---2017-08-09)
