### ISSUE TITLE
Dependencies for Ubuntu are specified for 12.04 that reached EOL

### ISSUE THREAD

**Issue by matkoniecz** [osmcode/node-osmium#92]
"Set dependencies up on Ubuntu Precise (12.04) like:" in https://github.com/osmcode/node-osmium#depends

EOL source: http://fridge.ubuntu.com/2017/03/15/ubuntu-12-04-precise-pangolin-reaches-end-of-life-on-april-28-2017/

**Comment by matkoniecz** [comment]
It would be desirable to see dependencies for 16.04.

**Comment by joto** [comment]
I removed the outdated dependency infos for Ubuntu 12.04. But the list of dependencies is probably still valid. If libosmium is installed and works, node-osmium should work, too.
