### ISSUE TITLE
Failed to uncompress data: buffer error

### ISSUE THREAD

**Issue by carles3** [osmcode/node-osmium#95]
Hello. 

I have problems working with "big" maps (pbf.osm);

**osmium error: failed to uncompress data: data error**

This error just appear with "big" maps, it not seems they are corrupted, can it be osmium version? I am working with a quite powerful laptop, 4cpu, 32gb ram. 

Thanks for your time.

**Comment by joto** [comment]
The error means that your OSM file is corrupted. There are many reasons why this could be the case, but without knowing the file and what exactly you did with it, we can't help you there.

**Comment by carles3** [comment]
I have downloaded the files from geofabrik, with node-osmium I extract ways/ road_relation of all European motorways. It seems that error just appear with big files, because I downloaded from same directory and I work with the same code. 

Thanks you .

**Comment by joto** [comment]
Again, if you don't supply any details, I can not reproduce this, so I assume the failure is on your side somewhere.

**Comment by carles3** [comment]
I am using [https://github.com/perliedman/osm-slope](url) software in order to get all motorway ways. 

Working with [http://download.geofabrik.de/europe.html](url) .osm.pbf files. 

I tried several countries, only the big ones give me an error, for exemple: France (3gb), Germany (5gb), Europe (18gb). 

Thanks you.

**Comment by joto** [comment]
I just checked http://download.geofabrik.de/europe/france-latest.osm.pbf and it is okay. Maybe something went wrong when you downloaded the file. The osm-slope program throws an unrelated error when I try it, so no help there. You can use [osmium-tool](http://osmcode.org/osmium-tool) to check whether your input file is okay (`osmium fileinfo -e` will give no error) or use it to extract part of the data (for instance all highways: `osmium tags-filter france-latest.osm.pbf w/highway -o highways.osm.pbf`) which would give you a smaller file which might then work with osm-slope. Or ask the author of osm-slope for help.

**Comment by carles3** [comment]
I have checked again geofabrik maps and I pretty sure the error comes from file size. 

```
Error: osmium error: failed to uncompress data: buffer error
    at Error (native)
    at exports.Reader.read (/data/OSM/osm-slope-master/node_modules/osmium/lib/osmium.js:100:25)
    at next (/data/OSM/osm-slope-master/index_parse_v1.2.js:107:25)
    at Immediate._onImmediate (/data/OSM/osm-slope-master/index_parse_v1.2.js:119:21)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
I have proceed with the whole Germany map, error appears, then I try with a sub-region like Hamburg, Bremen or Berlin (for example) and there is no error. 


Can it be a buffer memory limitation? Sorry for being persistent, I can not solve the problem. 
If there is no any option, I will try to extract part of data with tag-filter and then launch it again. 

Thanks for your time.

**Comment by ImreSamu** [comment]
@carles3 

>I have checked again geofabrik maps  .....
>I have proceed with the whole Germany map, error appears, 


there are md5sum files [http://download.geofabrik.de/europe/germany.html](http://download.geofabrik.de/europe/germany.html)  for every geofabric files.
*  [http://download.geofabrik.de/europe/germany.osh.pbf.md5](http://download.geofabrik.de/europe/germany.osh.pbf.md5)
* [https://en.wikipedia.org/wiki/Md5sum](https://en.wikipedia.org/wiki/Md5sum)

Have you checked the md5sum?

**Comment by joto** [comment]
Closing this as not reproducible.

**Comment by darkranjha** [comment]
@carles3, any resolution? I am getting the same error when trying to extract north american map (~10gb). 

**terminate called after throwing an instance of 'osmium::io_error'
  what():  failed to uncompress data: data error
Aborted (core dumped)**

Smaller regions work fine, but the big one gives me the same io:error when I try to extract using osrm-backend... 

Any help would be much appreciated (I also have a pretty decent PC... 8 cpus, 40GB memory)

**Dump:**

rahulinder01@DESKTOP-R0MU1GN:~/osrm-backend$ free
              total        used        free      shared  buff/cache   available
Mem:       41897076    20882668    20785056       17720      229352    20880676
Swap:      14514584       78832    14435752
rahulinder01@DESKTOP-R0MU1GN:~/osrm-backend$ osrm-extract /mnt/d/maps/north-america-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script profiles/car.lua
[info] Input file: north-america-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 16
[info] Parsing in progress..
[info] input file generated by 0.43.1
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
**terminate called after throwing an instance of 'osmium::io_error'
  what():  failed to uncompress data: data error
Aborted (core dumped)**
